using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
using System.Collections;

namespace FYP.Models
{
    public class CustomerDetails
    {
        // Customer_id is auto generated by database
        public string Customer_id { get; set; }

        [Required(ErrorMessage = "Please enter your Phone number")]
        [RegularExpression(@"[689]\d{7}", ErrorMessage = "Invalid Phone Number. Make sure you have entered a Singapore number")] // SG PhoneNo. start with (6/8/9) + 7 more digits 
        public int CustomerNo { get; set; }

        [Required(ErrorMessage = "Please enter your Birthdate")]
        [DataType(DataType.Date, ErrorMessage = "Birthdate must be in dd-MM-yyyy format")]
        [Remote(action: "CheckDate", controller: "Account")]
        public DateTime Date_of_birth { get; set; }


        [Required(ErrorMessage = "Please enter your Address")]
        [StringLength(200, MinimumLength = 10, ErrorMessage = "Address must be 10 characters or more")]
        public string Customer_Address { get; set; }

        //NULL value
        public DateTime Birthday_discount_id { get; set; }

        //FK from Users table
        public string UserEmail { get; set; }
    }
}
