using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
using System.Collections;

namespace FYP.Models
{
    public class Promotion
    {
        //  Promotion_discount_id is auto generated by database
        public int Promotion_discount_id { get; set; }

        [Required(ErrorMessage = "Please enter discount description")]
        [StringLength(100, ErrorMessage = "Item Name must be less than 100 characters")]
        public string Promotion_discount_Description { get; set; }


        [Required(ErrorMessage = "Please enter promotion percentage")]
        public int Promotion_percentage { get; set; }


        [Required(ErrorMessage = "Please enter promotion start date")]
        [DataType(DataType.Date, ErrorMessage = "Promotion_start_date must be in dd-MM-yyyy format")]
        public DateTime Promotion_start_date { get; set; }


        [Required(ErrorMessage = "Please enter promotion end date")]
        [DataType(DataType.Date, ErrorMessage = "Promotion_end_date must be in dd-MM-yyyy format")]
        public DateTime Promotion_end_date { get; set; }


    }
}
